### ISSUE TITLE
大佬好像不能用了，今天更新了下植物的样子

### ISSUE THREAD

**Issue by wanglihuaya** [yangdaozhao/ylgy#14]
第一关和之前不一样了

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Me-x** [comment]
同，不能用了 。等更新

**Comment by yangdaozhao** [comment]
已更新

**Comment by Jone2008** [comment]
> 已更新

已测试成功通过
