### ISSUE TITLE
今天更新不能用了

### ISSUE THREAD

**Issue by cyril-cheng** [yangdaozhao/ylgy#16]
今天小程序更新了，失效了

**Comment by yangdaozhao** [comment]
已更新 兄弟测试一下

**Comment by johnseed** [comment]
> 已更新 兄弟测试一下

可以了

**Comment by nathan-ey** [comment]
9-20,现在连名片都不加次数了，而且显示未加入羊群~

**Comment by deadjoker** [comment]
9.20显示挑战成功，已加入羊群，但名片里还是未加入羊群，次数也没有增加

**Comment by wyp010428** [comment]
现在可以通过改blocktype来重写，参考https://github.com/wyp010428/ylgy920

**Comment by yangdaozhao** [comment]
> 现在可以通过改blocktype来重写，参考https://github.com/wyp010428/ylgy920

现在这个版本就是
