### ISSUE TITLE
你好大佬

### ISSUE THREAD

**Issue by yuanshaocheng** [yangdaozhao/ylgy#2]
脚本是autojs还是什么呀

**Comment by yangdaozhao** [comment]
ios 的Quantumult X脚本 

你可以了解一下 https://www.kejiwanjia.com/jiaocheng/zheteng/notes/21016.html

**Comment by yuanshaocheng** [comment]
好的，谢谢，我直接用js里面的代码去伪装数据，哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月15日(周四) 上午10:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yangdaozhao/ylgy] 你好大佬 (Issue #2)

**Comment by yangdaozhao** [comment]
只要是能把接口返回值替换的都可以

**Comment by yuanshaocheng** [comment]
嗯呢 感谢感谢
&nbsp;

-----------------------------------------&nbsp;
袁绍成
数字中心


无锡高新人才发展集团有限公司


地址/Add：无锡市新吴区菱湖大道200号中国传感网国际创新园A楼402
电话/Tel：(0510)-85216829
手机/Mob：18706190693
www.nchr.com.cn




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 中午11:54
收件人: ***@***.***&gt;; 
抄送: "Yasin ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangdaozhao/ylgy] 你好大佬 (Issue #2)





 
只要是能把接口返回值替换的都可以
