### ISSUE TITLE
大佬，需要更新了

### ISSUE THREAD

**Issue by momoxinqing** [yangdaozhao/ylgy#23]

**Comment by nathan-ey** [comment]
9-23，即便第二关弄成白板，下面有些是掺杂不显示白板的。

**Comment by RuCu6** [comment]
确实失效了  贴个图

![1C349285-F41A-42C1-9EC8-86DCE9B9861C](https://user-images.githubusercontent.com/49463634/191880410-370bb7a0-20c7-43a5-807c-2d1a93de1665.png)

**Comment by LisonChan** [comment]
其实也还是能过，就是不能无脑点了
