### ISSUE TITLE
1

### ISSUE THREAD

**Issue by lki5** [yangdaozhao/ylgy#3]
大佬，这个重写怎么引用不进去？

**Comment by yangdaozhao** [comment]
是不是没开梯子

**Comment by lki5** [comment]
> 是不是没开梯子

开了，圈x开着呢，有节点，引用的时候显示Resource parser result with invalid Line
var body = $response.body

**Comment by yangdaozhao** [comment]
引用资源从写  导入仓库的[config.conf](https://github.com/yangdaozhao/ylgy/blob/master/config.conf) 然后玩一把

**Comment by yangdaozhao** [comment]
要打开 重写和MitM

**Comment by lki5** [comment]
成了，谢谢！
