### ISSUE TITLE
大佬能出个Shadowrocket 的脚本嘛谢谢

### ISSUE THREAD

**Issue by fafadoubi** [yangdaozhao/ylgy#4]

**Comment by yangdaozhao** [comment]
有空研究下写法

**Comment by Oldbai** [comment]
1. shadowsocket配置文件中打开https解密，生成一个新的ca证书，将证书安装进系统，然后去ios打开信任证书。
2. shadowsocket中配置->模块->新建模块，内容如下:
`
#!name=🍿️ ylgy
#!desc=羊了个羊

[Script]
Ylgy = type=http-response, pattern=^https?:\/\/cat\-match\.easygame2021\.com\/sheep\/v1\/game\/map\_info(.*)$, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/yangdaozhao/ylgy/master/ylgy.js, argument=

[MITM]
hostname = *.easygame2021.com
`

**Comment by Likunone** [comment]
没效果啊 怎么用

**Comment by bbhxwl** [comment]
> 1. shadowsocket配置文件中打开https解密，生成一个新的ca证书，将证书安装进系统，然后去ios打开信任证书。
> 2. shadowsocket中配置->模块->新建模块，内容如下:
> 
> #!name=🍿️ ylgy #!desc=羊了个羊 [Script] Ylgy = type=http-response, pattern=^https?://cat-match.easygame2021.com/sheep/v1/game/map_info(.*)$, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/yangdaozhao/ylgy/master/ylgy.js, argument= [MITM] hostname = *.easygame2021.com

我设置了后，是启动才可以么？我设置成功了，游戏不行。

**Comment by HowardTangHw** [comment]
> 1. shadowsocket配置文件中打开https解密，生成一个新的ca证书，将证书安装进系统，然后去ios打开信任证书。
> 2. shadowsocket中配置->模块->新建模块，内容如下:
> 
> #!name=🍿️ ylgy #!desc=羊了个羊 [Script] Ylgy = type=http-response, pattern=^https?://cat-match.easygame2021.com/sheep/v1/game/map_info(.*)$, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/yangdaozhao/ylgy/master/ylgy.js, argument= [MITM] hostname = *.easygame2021.com

@Oldbai https解密的域名要怎么配置？

**Comment by fafadoubi** [comment]
成功了谢谢 域名是*.easygame2021.com

**Comment by huangzhao-tech** [comment]
配置玩游戏就进不去了，是为什么呢

**Comment by huanhaunye** [comment]
> 配置玩游戏就进不去了，是为什么呢

设置--关于本机--拉到最下面有个信任证书--把新增的证书信任

**Comment by LIU-D** [comment]
全配置好后，第一关过去还是会到第二关……

**Comment by xiaxianguyue** [comment]
> 1. shadowsocket配置文件中打开https解密，生成一个新的ca证书，将证书安装进系统，然后去ios打开信任证书。
> 2. shadowsocket中配置->模块->新建模块，内容如下:
> 
> #!name=🍿️ ylgy #!desc=羊了个羊 [Script] Ylgy = type=http-response, pattern=^https?://cat-match.easygame2021.com/sheep/v1/game/map_info(.*)$, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/yangdaozhao/ylgy/master/ylgy.js, argument= [MITM] hostname = *.easygame2021.com

这个ss的https解密功能只有ios才有吗 ,我android的ss没有https解密功能

**Comment by kaisyaliu** [comment]
今天依然可用！

**Comment by yccccaaaa** [comment]
有没有配置好的图片发一个来看看

**Comment by drowtram** [comment]
好用，我跟我媳妇儿都加入羊群了。。。

**Comment by 1660667086** [comment]
> 1. shadowsocket配置文件中打开https解密，生成一个新的ca证书，将证书安装进系统，然后去ios打开信任证书。
> 2. shadowsocket中配置->模块->新建模块，内容如下:
> 
> #!name=🍿️ ylgy #!desc=羊了个羊 [Script] Ylgy = type=http-response, pattern=^https?://cat-match.easygame2021.com/sheep/v1/game/map_info(.*)$, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/yangdaozhao/ylgy/master/ylgy.js, argument= [MITM] hostname = *.easygame2021.com

牛逼啊

**Comment by zhangxiaocong** [comment]
第二步 shadowsocket中配置->模块->新建模块
shadowsocket 找不到配置选项  找不到在哪里新建模块 没有这个功能

**Comment by zhangxiaocong** [comment]
可否截图？@1660667086

**Comment by 1nfty** [comment]
参考上面大佬的写法，提供一个修改通关次数的脚本，开配置代理打开羊了个羊朋友圈排行榜食用。

shadowsocket配置文件中打开https解密，生成一个新的ca证书，将证书安装进系统，然后去ios打开信任证书。
shadowsocket中配置->模块->新建模块，内容如下:
#!name=🍿️ ylgy_leaderboard
#!desc=羊了个羊修改通关次数
[Script]
Ylgy = type=http-response, pattern=^https?://cat-match.easygame2021.com/sheep/v1/game/person_info(.*)$, requires-body=1, max-size=0, script-path=https://github.com/1nfty/ylgy/raw/master/ylgy_leaderboard.js, argument=
[MITM]
hostname = *.easygame2021.com

**Comment by sannnyu** [comment]
![Uploading 062B1C25-702F-446B-B0A4-34C3963C1C67.png…]()

**Comment by sannnyu** [comment]
![BCCC1EDA-1AED-4DB9-A46B-DEE63ACAE16F](https://user-images.githubusercontent.com/16554316/190872850-fa70fc96-832b-4f20-beb6-8588855bb963.png)
![012C52C3-F6BD-43A9-9ABA-4B7632E4235B](https://user-images.githubusercontent.com/16554316/190872852-542d212c-f120-48aa-b778-8337a637a8d7.png)
![2C38259D-7920-4633-8237-DAE3F5FE228B](https://user-images.githubusercontent.com/16554316/190872853-4dd6b6c4-88e4-42c9-b879-81b2b8594cea.png)
![50F0D4DC-2F8B-4E15-B8BD-EAEFCC9B184B](https://user-images.githubusercontent.com/16554316/190872855-bba61b08-811f-4228-abc0-fed6e382028a.png)
![98D785B3-FFEA-4B68-8D2D-4743BBBB159D](https://user-images.githubusercontent.com/16554316/190872856-d53a477d-5e45-47dd-8d22-a863af4d2b45.png)

**Comment by sannnyu** [comment]
@zhangxiaocong @1660667086 

> ![BCCC1EDA-1AED-4DB9-A46B-DEE63ACAE16F](https://user-images.githubusercontent.com/16554316/190872850-fa70fc96-832b-4f20-beb6-8588855bb963.png)
> ![012C52C3-F6BD-43A9-9ABA-4B7632E4235B](https://user-images.githubusercontent.com/16554316/190872852-542d212c-f120-48aa-b778-8337a637a8d7.png)
> ![2C38259D-7920-4633-8237-DAE3F5FE228B](https://user-images.githubusercontent.com/16554316/190872853-4dd6b6c4-88e4-42c9-b879-81b2b8594cea.png)
> ![50F0D4DC-2F8B-4E15-B8BD-EAEFCC9B184B](https://user-images.githubusercontent.com/16554316/190872855-bba61b08-811f-4228-abc0-fed6e382028a.png)
> ![98D785B3-FFEA-4B68-8D2D-4743BBBB159D](https://user-images.githubusercontent.com/16554316/190872856-d53a477d-5e45-47dd-8d22-a863af4d2b45.png)

**Comment by aitlp** [comment]
> 

贴个图：https://www.4spaces.org/yangdaozhao-ylgy/

**Comment by impl1874** [comment]
2022年9月20日19:24:46 亲测可用，需要修改下导入的模块内容，url变了
```
#!name=🍿️ ylgy
#!desc=羊了个羊
[Script]
Ylgy = type=http-response, pattern=^https?://cat-match-static.easygame2021.com/maps/(.*)$, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/yangdaozhao/ylgy/master/ylgy.js, argument=
[MITM]
hostname = *.easygame2021.com
```

**Comment by huajason** [comment]
> 1. shadowsocket配置文件中打开https解密，生成一个新的ca证书，将证书安装进系统，然后去ios打开信任证书。
> 2. shadowsocket中配置->模块->新建模块，内容如下:
> 
> #!name=🍿️ ylgy #!desc=羊了个羊 [Script] Ylgy = type=http-response, pattern=^https?://cat-match.easygame2021.com/sheep/v1/game/map_info(.*)$, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/yangdaozhao/ylgy/master/ylgy.js, argument= [MITM] hostname = *.easygame2021.com

第一步没找到

**Comment by leadscloud** [comment]
方法已失效，官方应该修改了。

**Comment by a952733** [comment]
今天用不了了
