### ISSUE TITLE
实测有用，开发者牛b

### ISSUE THREAD

**Issue by iamalexblue** [yangdaozhao/ylgy#8]

**Comment by yyu77458** [comment]
请问怎么用的呀，我引用资源显示错误

**Comment by iamalexblue** [comment]
- 首先打开设置，找到重写，然后选择规则资源，在其中添加规则（规则路径为 https://github.com/yangdaozhao/ylgy/blob/master/config.conf ，如果添加失败的话记得添加资源解析器：https://github.com/KOP-XIAO/QuantumultX/blob/master/Scripts/resource-parser.js ），规则名称随意，添加完成之后保存。
- 然后返回到设置界面，打开重写。
- 接着找到下方的 MitM，点击生成证书，接着点击配置证书，按照软件提示安装证书，信任证书。
- 完成之后回到设置界面打开 MitM
- 打开代理
- 打开羊了个羊，玩一把，你会发现第一关结束之后游戏并没有跳到第二关，不用管，接着玩一次第一关。
- 恭喜，你已经加入了羊群。

**Comment by pengdongxu** [comment]
我都打开了，还是进入了第二关😭，不知道哪里出问题了

**Comment by taka8rie** [comment]
> 我都打开了，还是进入了第二关😭，不知道哪里出问题了

你看看你是不是没有在 mitm那里添加 hostname = cat-match.easygame2021.com

**Comment by lzq7614402** [comment]
请大佬说的详细点 我搜到这里 请问 打开设置 是哪里的设置啊 不明白。。。

**Comment by iamalexblue** [comment]
> 请大佬说的详细点 我搜到这里 请问 打开设置 是哪里的设置啊 不明白。。。

打开 QuantumultX 的设置，然后按照步骤走

**Comment by lzq7614402** [comment]
下载这个软件 第一个添加失败了 解析器 在哪里添加呀 第一次用这个 找不到

**Comment by lrs95** [comment]
好像没用了

**Comment by PANGPANGDigital** [comment]
> 好像没用了

今天下午用了下，还是有效果的

**Comment by OneKillU** [comment]
规则添加失败，提示 Invalid Line <!DOCTYPE html>

**Comment by PANGPANGDigital** [comment]
> 规则添加失败，提示行无效

如果添加失败的话，先添加 资源解析器

**Comment by OneKillU** [comment]
> 

资源解析器已经添加了的，就是在配置文件里面把原来默认的example那个url替换成作者给的，还是不行哦

**Comment by OneKillU** [comment]
> > 规则添加失败，提示行无效
> 
> 如果添加失败的话，先添加 资源解析器

资源解析器已经添加了的，就是在配置文件里面把原来默认的example那个url替换成作者给的，还是不行哦

**Comment by cnfanhua** [comment]
添加这个地址试试（不行的话就打开资源解析器）：https://raw.githubusercontent.com/yangdaozhao/ylgy/master/config.conf

**Comment by OneKillU** [comment]
> 添加这个地址试试（不行的话就打开资源解析器）：https://raw.githubusercontent.com/yangdaozhao/ylgy/master/config.conf

您这个资源提示无法连接服务器，打开资源解析器提示无法定义资源解析器。。。太难了

**Comment by OneKillU** [comment]
> * https://github.com/yangdaozhao/ylgy/blob/master/config.conf

对不起是我傻B了，资源解析器前面的注释没打开，打开可以引用资源解析器了，但是保存资源的时候提示Result type error～

**Comment by garensix** [comment]
ios有没有无线道具的方法

**Comment by lty888** [comment]
还可以用啊，不错啊

**Comment by lynlive** [comment]
> 还可以用啊，不错啊

xd你怎么配置的啊，我都配置了不好使

**Comment by Yyzq12** [comment]
作者大佬 这是新的抓包思路  你看看希望对你有帮助。[新版抓包教程](https://www.coolapk.com/feed/39417494?shareKey=ZGM2ODljNGQwMTM2NjMyOTM1Nzg~&shareUid=23137047&shareFrom=com.coolapk.app_5.0.1)

**Comment by xp-git** [comment]
怎么添加引用资源的时候报错了。

**Comment by tiec0de** [comment]
简直完美！

**Comment by hengzi111** [comment]
> > * https://github.com/yangdaozhao/ylgy/blob/master/config.conf
> 
> 对不起是我傻B了，资源解析器前面的注释没打开，打开可以引用资源解析器了，但是保存资源的时候提示结果类型错误～

我也是同样的问题，兄弟你解决了吗

**Comment by hengzi111** [comment]
Result type error  这个问题有没有大佬帮助解答一下  十分感谢

**Comment by abbyabeatgmaildotcom** [comment]
可以用，妥妥的，已经设置过的就不用再设置证书了，直接加一条重写规则就行了

**Comment by krubera-cmd** [comment]
好像不行了，第二关出现白板，通关没记录

**Comment by qrpengx** [comment]
> 好像不行了，第二关出现白板，通关没记录
我这里也不行了

**Comment by YuaAriga** [comment]
> > 好像不行了，第二关出现白板，通关没记录
> 
> 我这里也不行了

是不行了
