### ISSUE TITLE
- 首先打开设置，找到重写，然后选择规则资源，在其中添加规则（规则路径为 https://github.com/yangdaozhao/ylgy/blob/master/config.conf ，如果添加失败的话记得添加资源解析器：https://github.com/KOP-XIAO/QuantumultX/blob/master/Scripts/resource-parser.js ），规则名称随意，添加完成之后保存。

### ISSUE THREAD

**Issue by yangdaozhao** [yangdaozhao/ylgy#9]
- 首先打开设置，找到重写，然后选择规则资源，在其中添加规则（规则路径为 https://github.com/yangdaozhao/ylgy/blob/master/config.conf ，如果添加失败的话记得添加资源解析器：https://github.com/KOP-XIAO/QuantumultX/blob/master/Scripts/resource-parser.js ），规则名称随意，添加完成之后保存。
- 然后返回到设置界面，打开重写。
- 接着找到下方的 MitM，点击生成证书，接着点击配置证书，按照软件提示安装证书，信任证书。
- 完成之后回到设置界面打开 MitM
- 打开代理
- 打开羊了个羊，玩一把，你会发现第一关结束之后游戏并没有跳到第二关，不用管，接着玩一次第一关。
- 恭喜，你已经加入了羊群。

_Originally posted by @iamalexblue in https://github.com/yangdaozhao/ylgy/issues/8#issuecomment-1248027573_

**Comment by yyu77458** [comment]
哇，保姆级教程，谢谢大佬 #

**Comment by Yyzq12** [comment]
大佬现在这个方法进不了羊群了，这是新方法删除小程序重新进抓包，点击开始后回小黄鸟搜90020，会出现一个txt链接，长按重写，响应最下面编辑内容，将blockTypeData后面大括弧内容清空保存，再去删除小程序重新进，要开着抓包进入关卡，这时候第二关就全是白板，全部点完便搞定
 [新抓包思路 ](https://www.coolapk.com/feed/39417494?shareKey=ZGM2ODljNGQwMTM2NjMyOTM1Nzg~&shareUid=23137047&shareFrom=com.coolapk.app_5.0.1)

**Comment by yangdaozhao** [comment]
> 
懂了 有空更新

**Comment by yangdaozhao** [comment]
> 大佬现在这个方法进不了羊群了，这是新方法删除小程序重新进抓包，点击开始后回小黄鸟搜90020，会出现一个txt链接，长按重写，响应最下面编辑内容，将blockTypeData后面大括弧内容清空保存，再去删除小程序重新进，要开着抓包进入关卡，这时候第二关就全是白板，全部点完便搞定 [新抓包思路 ](https://www.coolapk.com/feed/39417494?shareKey=ZGM2ODljNGQwMTM2NjMyOTM1Nzg~&shareUid=23137047&shareFrom=com.coolapk.app_5.0.1)

已更新

**Comment by impl1874** [comment]
2022年9月20日18:53:28 亲测成功，注意09-20号`[README.md](https://github.com/yangdaozhao/ylgy)`更新内容：删除小程序
